language: node_js

cache:
  directories:
  - node_modules

node_js:
- 6.9.4

install:
- echo "Install dependencies..."
- npm install

script:
- echo "Building distributable..."
- npm run build
- npm run deploy